# Cloud Build configuration
# Frontend build args are passed via substitutions from GitHub Actions
# Backend secrets are pulled from Secret Manager at runtime

substitutions:
  _VITE_SUPABASE_URL: ''
  _VITE_SUPABASE_ANON_KEY: ''

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/goal-tracker'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '--build-arg'
      - 'VITE_API_URL='
      - '--build-arg'
      - 'VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}'
      - '--build-arg'
      - 'VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/goal-tracker'

  # Deploy container image to Cloud Run with secrets from Secret Manager
  # Use --clear-env-vars to remove any conflicting env vars, then set secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy goal-tracker \
          --image gcr.io/$PROJECT_ID/goal-tracker \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --clear-env-vars \
          --set-secrets=SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_ANON_KEY=SUPABASE_ANON_KEY:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest,SUPABASE_JWKS_URL=SUPABASE_JWKS_URL:latest

images:
  - 'gcr.io/$PROJECT_ID/goal-tracker'
