#!/bin/bash
# Manual deployment steps for Goal Tracker

echo "================================================"
echo "Manual Deployment Guide for Cloud Run"
echo "================================================"
echo ""
echo "Follow these steps to deploy your app:"
echo ""

echo "1. Build and push the Docker image:"
echo "   gcloud builds submit --tag gcr.io/goal-tracker-477205/goal-tracker --project goal-tracker-477205 -f Dockerfile.cloudrun ."
echo ""

echo "2. Deploy to Cloud Run:"
echo "   gcloud run deploy goal-tracker \\"
echo "     --image gcr.io/goal-tracker-477205/goal-tracker \\"
echo "     --platform managed \\"
echo "     --region us-central1 \\"
echo "     --allow-unauthenticated \\"
echo "     --set-env-vars SUPABASE_URL=https://bnmdrvslwmuimlpkqqfq.supabase.co \\"
echo "     --set-env-vars SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJubWRydnNsd211aW1scGtxcWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMTg5MDEsImV4cCI6MjA3Nzc5NDkwMX0.4Sa_IlZ_KLetqlDPeHyYhueDWw72XqpPwZDoOERQjKg \\"
echo "     --project goal-tracker-477205"
echo ""

echo "3. Get the deployed URL:"
echo "   gcloud run services describe goal-tracker --region us-central1 --format 'value(status.url)'"
echo ""

echo "4. Test the deployment:"
echo "   curl https://your-service-url.run.app/health"
echo ""

echo "================================================"
echo "Alternative: Use Cloud Console"
echo "================================================"
echo ""
echo "1. Go to: https://console.cloud.google.com/run?project=goal-tracker-477205"
echo "2. Click 'CREATE SERVICE'"
echo "3. Select 'Deploy one revision from an existing container image'"
echo "4. Click 'SELECT' and choose: gcr.io/goal-tracker-477205/goal-tracker"
echo "5. Set service name: goal-tracker"
echo "6. Select region: us-central1"
echo "7. Under 'Container, Variables & Secrets, Connections, Security':"
echo "   - Add environment variables:"
echo "     SUPABASE_URL=https://bnmdrvslwmuimlpkqqfq.supabase.co"
echo "     SUPABASE_ANON_KEY=<your-anon-key>"
echo "8. Set 'Allow unauthenticated invocations'"
echo "9. Click 'CREATE'"
echo ""
